name: Build iOS (No Sign)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
      - name: Fix GitHub SSH
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Install Pods
        run: |
          pod install

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build Archive (No Code Sign)
        run: |
          xcodebuild \
          -workspace ORBIT.xcworkspace \
          -scheme ORBIT \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/ORBIT.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          archive

      - name: Export IPA (No Sign)
        run: |
          mkdir -p build/ipa

          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ORBIT.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ipa